services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/app

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: