services:

  user_service:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB : user_db
    ports:
      - "5433:5432"
    
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: